image: ruby:3.0.2

cache:
  paths:
    - vendor/

build:
  stage: build
  script:
    - bundle install --deployment --path vendor/bundle
    - bundle exec rubocop
    - bundle exec rspec --pattern service_module_internal/**/*_spec.rb

stages:
  - build
