inherit_from: .rubocop_todo.yml
AllCops:
  NewCops: enable
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
    - '../vendor/**/*'
    - '../tmp/**/*'
    - '../db/schema.rb'
    - '../db/migrate/*'
    - '../bin/*'
Layout/LineLength:
  Max: 120
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Metrics/BlockLength:
  ExcludedMethods:
    - before
    - configure
    - context
    - define
    - describe
    - draw
    - factory
    - feature
    - has_one
    - included
    - it
    - let
    - namespace
    - scenario
    - shared_examples
    - shared_examples_for
    - test
    - setup
Metrics/ModuleLength:
  Max: 225
Rails/HelperInstanceVariable:
  Enabled: false
Rails/LexicallyScopedActionFilter:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
Style/Documentation:
  Enabled: false
Style/RaiseArgs:
  EnforcedStyle: compact
