# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'
gem 'activeresource', git: 'https://github.com/ArthurWD/activeresource'
gem 'acts_as_tenant', git: 'https://github.com/ErwinM/acts_as_tenant', ref: '1ba28'
gem 'bunny', '~> 2.6.1'
gem 'combustion', '~> 0.5.5'
gem 'doorkeeper'
gem 'doorkeeper-jwt'
gem 'json-ld'
gem 'linked_rails', git: 'https://github.com/ontola/linked_rails', branch: 'collections-dsl'
gem 'linked_rails-auth', git: 'https://github.com/ontola/linked_rails-auth'
gem 'oauth2'
gem 'oj'
gem 'pragmatic_context'
gem 'pundit'
gem 'rails', '~> 6.0'
gem 'rake'
gem 'rdf'
gem 'rdf-n3'
gem 'rdf-rdfa'
gem 'rdf-rdfxml'
gem 'rdf-turtle'
gem 'rdf-vocab'
gem 'rfc-822', '~> 0.4.1'
gem 'rspec-rails'
gem 'rubocop', '~> 0.92.0'
gem 'rubocop-rails', '~> 2.5.2'
gem 'rubocop-rspec', '~> 1.39.0'
gem 'shoulda-matchers'
gem 'sidekiq'
gem 'sqlite3'
gem 'uri_template'
gem 'webmock'
