# frozen_string_literal: true

source 'https://rubygems.org'

gem 'active_model_serializers', '= 0.10.7'
gem 'activerecord'
gem 'activeresource', git: 'https://github.com/ArthurWD/activeresource'
gem 'acts_as_tenant', git: 'https://github.com/ArthurWD/acts_as_tenant', branch: :master
gem 'bunny', '~> 2.6.1'
gem 'combustion', '~> 0.5.5'
gem 'oauth2'
gem 'pragmatic_context'
gem 'pundit'
gem 'rails'
gem 'rake'
gem 'rdf'
gem 'rdf-serializers', git: 'https://github.com/argu-co/rdf-serializers', branch: 'master'
gem 'rfc-822', '~> 0.4.1'
gem 'rspec-rails'
gem 'rubocop'
gem 'rubocop-rspec'
gem 'shoulda-matchers', branch: :master, git: 'https://github.com/thoughtbot/shoulda-matchers'
gem 'sqlite3'
gem 'uri_template'
gem 'webmock'
