# frozen_string_literal: true

source 'https://rubygems.org'

gem 'active_response', git: 'https://github.com/ontola/active_response', branch: :master
gem 'activerecord'
gem 'activeresource', git: 'https://github.com/ArthurWD/activeresource'
gem 'acts_as_tenant', git: 'https://github.com/ErwinM/acts_as_tenant', ref: '1ba28'
gem 'bunny', '~> 2.6.1'
gem 'combustion', '~> 0.5.5'
gem 'doorkeeper'
gem 'fast_jsonapi', git: 'https://github.com/fast-jsonapi/fast_jsonapi', ref: '2de80d48896751'
gem 'json-ld'
gem 'linked_rails', git: 'https://github.com/ontola/linked_rails', branch: 'apex-rs'
gem 'linked_rails-auth', git: 'https://github.com/ontola/linked_rails-auth'
gem 'oauth2'
gem 'oj'
gem 'pragmatic_context'
gem 'pundit'
gem 'rails', '~> 6.0'
gem 'rake'
gem 'rdf'
gem 'rdf-n3'
gem 'rdf-rdfa'
gem 'rdf-rdfxml'
gem 'rdf-serializers', git: 'https://github.com/ontola/rdf-serializers', branch: 'fast-jsonapi'
gem 'rdf-turtle'
gem 'rdf-vocab'
gem 'rfc-822', '~> 0.4.1'
gem 'rspec-rails'
gem 'rubocop'
gem 'rubocop-rails'
gem 'rubocop-rspec'
gem 'shoulda-matchers'
gem 'sidekiq'
gem 'sqlite3'
gem 'uri_template'
gem 'webmock'
