# General IRI's
action_items_iri: "{/parent_iri*}{/id}"
action_lists_iri: "{/parent_iri*}/actions"
activities_iri: "{/root_id}/activities{/id}"
activities_collection_canonical: "{/parent_iri*}/feed{?filter%5B%5D*,page,page_size,type,before,complete}"
activities_collection_iri: "{/parent_iri*}/feed{?filter%5B%5D*,page,page_size,type,before,complete}"
actors_iri: "{/parent_iri*}/actors"
announcements_iri: "/announcements{/id}"
arguments_iri: "{/root_id}/a{/id}{?destroy}"
arguments_collection_canonical: "{/parent_iri*}/arguments{?display,filter%5B%5D*,page,page_size,type,before}"
arguments_collection_iri: "{/parent_iri*}/arguments{?display,filter%5B%5D*,page,page_size,type,before}"
attachments_collection_canonical: "{/parent_iri*}/attachments{?filter%5B%5D*,page,page_size,type,before}"
attachments_collection_iri: "{/parent_iri*}/attachments{?filter%5B%5D*,page,page_size,type,before}"
blog_posts_iri: "{/root_id}/posts{/id}{?destroy}"
blog_posts_collection_canonical: "{/parent_iri*}/posts{?display,filter%5B%5D*,page,page_size,type,before}"
blog_posts_collection_iri: "{/parent_iri*}/posts{?display,filter%5B%5D*,page,page_size,type,before}"
blogs_collection_canonical: "{/parent_iri*}/blogs{?display,filter%5B%5D*,page,page_size,type,before}"
blogs_collection_iri: "{/parent_iri*}/blogs{?display,filter%5B%5D*,page,page_size,type,before}"
categories_iri: "{/root_id}/categories{/id}{?destroy}"
categories_collection_canonical: "{/parent_iri*}/categories{?display,filter%5B%5D*,page,page_size,type,before}"
categories_collection_iri: "{/parent_iri*}/categories{?display,filter%5B%5D*,page,page_size,type,before}"
comments_iri: "{/root_id}/c{/id}{?destroy,parent_id}"
comments_collection_canonical: "{/parent_iri*}/comments{?display,filter%5B%5D*,page,page_size,type,before}"
comments_collection_iri: "{/parent_iri*}/c{?display,filter%5B%5D*,page,page_size,type,before}"
confirmations_iri: "/users/confirmation{?user%5Bemail%5D}"
conversions_iri: "{/parent_iri*}/conversion"
conversions_collection_canonical: "{/parent_iri*}/conversion{?display,filter%5B%5D*,page,page_size,type,before}"
conversions_collection_iri: "{/parent_iri*}/conversion{?display,filter%5B%5D*,page,page_size,type,before}"
con_arguments_iri: "{/root_id}/con{/id}{?destroy}"
con_arguments_collection_canonical: "{/parent_iri*}/con_arguments{?display,filter%5B%5D*,page,page_size,type,before}"
con_arguments_collection_iri: "{/parent_iri*}/cons{?display,filter%5B%5D*,page,page_size,type,before}"
container_nodes_iri: "{/root_id}{/id}"
container_nodes_collection_canonical: "{/parent_iri*}/container_nodes{?display,filter%5B%5D*,page,page_size,type,before}"
container_nodes_collection_iri: "{/parent_iri*}/container_nodes{?display,filter%5B%5D*,page,page_size,type,before}"
creative_works_iri: "{/root_id}/creative_works{/id}"
creative_works_collection_canonical: "{/parent_iri*}/creative_works{?display,filter%5B%5D*,page,page_size,type,before}"
creative_works_collection_iri: "{/parent_iri*}/creative_works{?display,filter%5B%5D*,page,page_size,type,before}"
current_actors_iri: "/c_a"
custom_actions_iri: "{/parent_iri*}/custom_actions{/id}"
custom_actions_collection_canonical: "{/parent_iri*}/custom_actions{?display,filter%5B%5D*,page,page_size,type,before}"
custom_actions_collection_iri: "{/parent_iri*}/custom_actions{?display,filter%5B%5D*,page,page_size,type,before}"
custom_menu_items_iri: "{/parent_iri*}/menus/{menu_type}#menu_item_{id}"
custom_menu_items_canonical_iri: "{/parent_iri*}/custom_menu_items{/id}"
custom_menu_items_collection_canonical: "{/parent_iri*}/custom_menu_items{?display,filter%5B%5D*,page,page_size,type,before}"
custom_menu_items_collection_iri: "{/parent_iri*}/custom_menu_items{?display,filter%5B%5D*,page,page_size,type,before}"
dashboards_collection_canonical: "{/parent_iri*}/dashboards{?display,filter%5B%5D*,page,page_size,type,before}"
dashboards_collection_iri: "{/parent_iri*}/dashboards{?display,filter%5B%5D*,page,page_size,type,before}"
decisions_iri: "{/parent_iri*}/decision{/id}"
decisions_collection_canonical: "{/parent_iri*}/decision{?display,page,type,before,state}"
decisions_collection_iri: "{/parent_iri*}/decision{?display,page,type,before,state}"
delete_iri: "{/parent_iri*}/delete"
direct_messages_iri: "{/parent_iri*}/dm"
direct_messages_collection_canonical: "{/parent_iri*}/dm{?display,filter%5B%5D*,page,page_size,type,before}"
direct_messages_collection_iri: "{/parent_iri*}/dm{?display,filter%5B%5D*,page,page_size,type,before}"
discussions_collection_canonical: "{/parent_iri*}/discussions{?display,filter%5B%5D*,page,page_size,type,before}"
discussions_collection_iri: "{/parent_iri*}/discussions{?display,filter%5B%5D*,page,page_size,type,before}"
documents_iri: "{/name}"
drafts_collection_canonical: "{/parent_iri*}/drafts{?display,filter%5B%5D*,page,page_size,type,before}"
drafts_collection_iri: "{/parent_iri*}/drafts{?display,filter%5B%5D*,page,page_size,type,before}"
edges_iri: "/edges{/id}"
edges_canonical_iri: "/edges{/id}"
edit_iri: "{/parent_iri*}/edit{?form,reset_password_token}"
employments_iri: "{/parent_iri*}/employments{/id}{?email_address%5Bprimary%5D}"
employments_collection_canonical: "{/parent_iri*}/employments{?display,filter%5B%5D*,page,page_size,type,before}"
employments_collection_iri: "{/parent_iri*}/employments{?display,filter%5B%5D*,page,page_size,type,before}"
employment_moderations_iri: "{/parent_iri*}/moderation{/id}{?email_address%5Bprimary%5D}"
employment_moderations_collection_canonical: "{/parent_iri*}/moderation{?display,filter%5B%5D*,page,page_size,type,before}"
employment_moderations_collection_iri: "{/parent_iri*}/moderation{?display,filter%5B%5D*,page,page_size,type,before}"
email_addresses_iri: "{/parent_iri*}/email_addresses{/id}{?email_address%5Bprimary%5D}"
email_addresses_collection_canonical: "{/parent_iri*}/email_addresses{?display,filter%5B%5D*,page,page_size,type,before}"
email_addresses_collection_iri: "{/parent_iri*}/email_addresses{?display,filter%5B%5D*,page,page_size,type,before}"
email_conflicts_iri: "{/parent_iri*}/email_conflict"
export_iri: "{/parent_iri*}/exports"
exports_iri: "{/root_id*}/exports{/id}{?destroy}"
exports_collection_canonical: "{/parent_iri*}/exports{?display,filter%5B%5D*,page,page_size,type,before}"
exports_collection_iri: "{/parent_iri*}/exports{?display,filter%5B%5D*,page,page_size,type,before}"
favorites_iri: "{/root_id}/favorites{/id}"
favorites_collection_canonical: "{/parent_iri*}/favorites{?display,filter%5B%5D*,page,page_size,type,before}"
favorites_collection_iri: "{/parent_iri*}/favorites{?display,filter%5B%5D*,page,page_size,type,before}"
favorites_feed_iri: "/feed"
feeds_iri: "{/parent_iri*}/feed{.format}{?complete}"
follows_iri: "{/root_id}/follows{/id}{?gid,follow_type}"
follows_collection_canonical: "{/parent_iri*}/follows{?display,filter%5B%5D*,page,page_size,type,before}"
follows_collection_iri: "{/parent_iri*}/follows{?display,filter%5B%5D*,page,page_size,type,before}"
forums_collection_canonical: "{/parent_iri*}/forums{?display,filter%5B%5D*,page,page_size,type,before}"
forums_collection_iri: "{/parent_iri*}/forums{?display,filter%5B%5D*,page,page_size,type,before}"
grant_tree_nodes_iri: "/edges{/edge_id}/permissions"
grant_tree_permission_groups_iri: "/edges{/edge_id}/permissions/g{/group_id}"
grant_tree_permissions_iri: "/edges{/edge_id}/permissions/g{/group_id}{/resource_type}"
grants_iri: "{/root_id}/grants{/id}"
grants_collection_canonical: "{/parent_iri*}/grants{?display,page,type,before,edge_id,group_id}"
grants_collection_iri: "{/parent_iri*}/grants{?display,page,type,before,edge_id,group_id}"
grant_sets_iri: "/grant_sets{/id}"
grant_sets_collection_iri: "/grant_sets{?display,page,type,before,edge_id,group_id}"
groups_iri: "{/root_id}/g{/id}"
groups_collection_canonical: "{/parent_iri*}/groups{?display,filter%5B%5D*,page,page_size,type,before}"
groups_collection_iri: "{/parent_iri*}/g{?display,filter%5B%5D*,page,page_size,type,before}"
group_memberships_iri: "{/root_id}/group_memberships{/id}"
group_memberships_collection_canonical: "{/parent_iri*}/group_memberships{?display,filter%5B%5D*,page,page_size,type,before}"
group_memberships_collection_iri: "{/parent_iri*}/group_memberships{?display,filter%5B%5D*,page,page_size,type,before}"
guest_users_iri: "/sessions{/id}"
incidents_iri: "{/root_id}/incidents{/id}"
incidents_collection_canonical: "{/parent_iri*}/incidents{?display,filter%5B%5D*,page,page_size,type,before}"
incidents_collection_iri: "{/parent_iri*}/incidents{?display,filter%5B%5D*,page,page_size,type,before}"
identities_iri: "/identities{/id}"
info_iri: "/i{/id}"
interventions_iri: "{/root_id}/interventies{/id}"
interventions_collection_canonical: "{/parent_iri*}/interventies{?display,filter%5B%5D*,page,page_size,type,before}"
interventions_collection_iri: "{/parent_iri*}/interventies{?display,filter%5B%5D*,page,page_size,type,before}"
intervention_types_iri: "{/root_id}/interventie_types{/id}"
intervention_types_collection_canonical: "{/parent_iri*}/interventie_types{?display,filter%5B%5D*,page,page_size,type,before}"
intervention_types_collection_iri: "{/parent_iri*}/interventie_types{?display,filter%5B%5D*,page,page_size,type,before}"
invites_iri: "{/parent_iri*}/invites"
languages_iri: "/u/language{/language}"
linked_collections_iri: "{/root_id}{/forum}/od{/id}"
linked_collection_members_iri: "{/parent_iri*}{?display,filter%5B%5D*,page,page_size,type,before}"
linked_records_iri: "{/root_id}{/container_node_id}/od{/linked_record_id}"
logs_iri: "{/parent_iri*}/log"
manifests_iri: "{/root_id}/manifest"
measures_iri: "{/root_id}/voorbeelden{/id}"
measures_collection_canonical: "{/parent_iri*}/voorbeelden{?display,filter%5B%5D*,page,page_size,type,before}"
measures_collection_iri: "{/parent_iri*}/voorbeelden{?display,filter%5B%5D*,page,page_size,type,before}"
measure_types_iri: "{/root_id}/measure_types{/id}"
measure_types_collection_canonical: "{/parent_iri*}/measure_types{?display,filter%5B%5D*,page,page_size,type,before}"
measure_types_collection_iri: "{/parent_iri*}/measure_types{?display,filter%5B%5D*,page,page_size,type,before}"
media_objects_iri: "{/root_id}/media_objects{/id}"
media_objects_collection_canonical: "{/parent_iri*}/media_objects{?filter%5B%5D*,page,type,before}"
media_objects_collection_iri: "{/parent_iri*}/media_objects{?filter%5B%5D*,page,type,before}"
menu_lists_iri: "{/parent_iri*}/menus"
menus_iri: "/menus{/id}"
motions_iri: "{/root_id}/m{/id}{?destroy,start_motion_tour,happening_id}"
motions_collection_canonical: "{/parent_iri*}/motions{?display,filter%5B%5D*,page,page_size,type,before}"
motions_collection_iri: "{/parent_iri*}/m{?display,filter%5B%5D*,page,page_size,type,before}"
moves_iri: "{/parent_iri*}/move{?move%5Bnew_parent_id%5D}"
new_iri: "{/parent_iri*}/new"
new_container_node_iri: "/container_nodes/new{?display,filter%5B%5D*,page,page_size,type,before}"
notifications_iri: "/n{/id}"
notifications_collection_canonical: "/n{?display,filter%5B%5D*,page,page_size,type,before}"
notifications_collection_iri: "/n{?display,filter%5B%5D*,page,page_size,type,before}"
open_data_portals_collection_canonical: "{/parent_iri*}/open_data_portals{?display,filter%5B%5D*,page,page_size,type,before}"
open_data_portals_collection_iri: "{/parent_iri*}/open_data_portals{?display,filter%5B%5D*,page,page_size,type,before}"
page_menu_lists_iri: ""
pages_canonical_iri: "/o{/id}"
pages_iri: ""
pages_collection_canonical: "{/parent_iri*}/organizations{?display,filter%5B%5D*,page,page_size,type,before}"
pages_collection_iri: "{/parent_iri*}/o{?display,filter%5B%5D*,page,page_size,type,before}"
passwords_iri: "/users/password"
permitted_actions_iri: "/permitted_actions{/id}{?destroy,start_motion_tour,happening_id}"
permitted_actions_collection_iri: "/permitted_actions{?display,filter%5B%5D*,page,page_size,type,before}"
phases_iri: "/phases{/id}"
phases_collection_canonical: "{/parent_iri*}/phases{?display,filter%5B%5D*,page,page_size,type,before}"
phases_collection_iri: "{/parent_iri*}/phases{?display,filter%5B%5D*,page,page_size,type,before}"
places_iri: "/places{/id}"
placements_iri: "/placements{/id}"
placements_collection_canonical: "{/parent_iri*}/placements{?display,filter%5B%5D*,page,page_size,type,before}"
placements_collection_iri: "{/parent_iri*}/placements{?display,filter%5B%5D*,page,page_size,type,before}"
pro_arguments_iri: "{/root_id}/pro{/id}{?destroy}"
pro_arguments_collection_canonical: "{/parent_iri*}/pro_arguments{?display,filter%5B%5D*,page,page_size,type,before}"
pro_arguments_collection_iri: "{/parent_iri*}/pros{?display,filter%5B%5D*,page,page_size,type,before}"
profiles_iri: "/profiles{/id}"
projects_iri: "{/root_id}/projects{/id}"
projects_collection_canonical: "{/parent_iri*}/projects{?display,filter%5B%5D*,page,page_size,type,before}"
projects_collection_iri: "{/parent_iri*}/projects{?display,filter%5B%5D*,page,page_size,type,before}"
publications_iri: "/publications{/id}"
questions_iri: "{/root_id}/q{/id}{?destroy,happening_id,sort}"
questions_collection_canonical: "{/parent_iri*}/questions{?display,filter%5B%5D*,page,page_size,type,before}"
questions_collection_iri: "{/parent_iri*}/q{?display,filter%5B%5D*,page,page_size,type,before}"
settings_iri: "{/parent_iri*}/settings{?tab}"
shortnames_iri: "/shortnames{/id}"
shortnames_collection_canonical: "{/parent_iri*}/shortnames{?display,filter%5B%5D*,page,page_size,type,before}"
shortnames_collection_iri: "{/parent_iri*}/shortnames{?display,filter%5B%5D*,page,page_size,type,before}"
sources_iri: "{/parent_iri*}/s{/id}"
statistics_iri: "{/parent_iri*}/statistics"
submissions_iri: "{/parent_iri*}/submission"
submissions_collection_canonical: "{/parent_iri*}/submissions{?display,filter%5B%5D*,page,page_size,type,before}"
submissions_collection_iri: "{/parent_iri*}/submissions{?display,filter%5B%5D*,page,page_size,type,before}"
surveys_iri: "{/root_id}/surveys{/id}"
surveys_collection_canonical: "{/parent_iri*}/surveys{?display,filter%5B%5D*,page,page_size,type,before}"
surveys_collection_iri: "{/parent_iri*}/surveys{?display,filter%5B%5D*,page,page_size,type,before}"
terms_iri: "/terms"
tokens_iri: "/tokens{/secret}"
bearer_tokens_iri: "/tokens{/secret}"
email_tokens_iri: "/tokens{/secret}"
tokens_collection_iri: "/tokens{/token_type}/g{/group_id}{?display,page,type,before}"
bearer_tokens_collection_iri: "/tokens/bearer/g{/group_id}{?display,page,type}"
email_tokens_collection_iri: "/tokens/email/g{/group_id}{?display,page,type}"
risks_iri: "{/root_id}/gevaren{/id}"
risks_collection_canonical: "{/parent_iri*}/gevaren{?display,filter%5B%5D*,page,page_size,type,before}"
risks_collection_iri: "{/parent_iri*}/gevaren{?display,filter%5B%5D*,page,page_size,type,before}"
scenarios_iri: "{/root_id}/scenarios{/id}"
scenarios_collection_canonical: "{/parent_iri*}/scenarios{?display,filter%5B%5D*,page,page_size,type,before}"
scenarios_collection_iri: "{/parent_iri*}/scenarios{?display,filter%5B%5D*,page,page_size,type,before}"
setups_iri: "/u/setup"
topics_iri: "{/root_id}/t{/id}{?destroy}"
topics_collection_canonical: "{/parent_iri*}/topics{?display,filter%5B%5D*,page,page_size,type,before}"
topics_collection_iri: "{/parent_iri*}/t{?display,filter%5B%5D*,page,page_size,type,before}"
trash_iri: "{/parent_iri*}/trash"
untrash_iri: "{/parent_iri*}/untrash"
users_canonical_iri: "/u{/id}"
users_iri: "{/root_id}/u{/id}"
vocabularies_iri: "{/parent_iri*}/ns/core"
vote_iri: "{/parent_iri*}/vote{?for}"
votes_iri: "{/root_id}/votes{/id}"
votes_collection_canonical: "{/parent_iri*}/votes{?filter%5B%5D*,page,type,before,for}"
votes_collection_iri: "{/parent_iri*}/votes{?filter%5B%5D*,page,type,before,for}"
vote_events_iri: "{/parent_iri*}/vote_events{/id}"
vote_events_collection_canonical: "{/parent_iri*}/vote_events{?display,filter%5B%5D*,page,page_size,type,before}"
vote_events_collection_iri: "{/parent_iri*}/vote_events{?display,filter%5B%5D*,page,page_size,type,before}"
widgets_iri: "/widgets{/id}"
widgets_collection_canonical: "{/parent_iri*}/widgets{?display,filter%5B%5D*,page,page_size,type,before}"
widgets_collection_iri: "{/parent_iri*}/widgets{?display,filter%5B%5D*,page,page_size,type,before}"
# Argu Service
new_vote: "{/voteable_path*}/votes/new{?confirm,r,vote%5Bfor%5D}"
new_pasword: "/users/password/new"
user_confirmation: "/users/confirmation{?confirmation_token}"
user_confirm: "/users/confirm"
user_connect: "/u{/id}/connect{?token}"
user_registration: "/users"
user_set_password: "/users/password/edit{?reset_password_token}"
user_unlock: "/users/unlock{?unlock_token}"
search_results_iri: "{/parent_iri*}/search{?q,filter%5B%5D*,page,page_size}"
setup_iri: "/u/setup"
spi_authorize: "/spi/authorize{?resource_type,resource_id,resource_iri,authorize_action}"
spi_find_tenant: "/_public/spi/find_tenant{?iri}"
spi_oauth_token: "/spi/oauth/token"
spi_email_addresses: "/spi/email_addresses{?email}"
default_vote_event_votes_index: "{/parent_iri*}/vote_events/default"
# Token Service
bearer_token: "{/root_id}/tokens/{access_token}"
verify_token: "{/root_id}/tokens/verify{?jwt}"
# Email Service
email_spi_create: "/email/spi/emails"
email_index: "/email/emails"
