# General IRI's
action_items_iri: "{/parent_iri*}{/id}"
action_lists_iri: "{/parent_iri*}/actions"
activities_iri: "{/root_id}/activities{/id}"
activities_collection_canonical: "{/parent_iri*}/feed{?filter%5B%5D,page,page_size,type,before,complete}"
activities_collection_iri: "{/parent_iri*}/feed{?filter%5B%5D,page,page_size,type,before,complete}"
actors_iri: "{/parent_iri*}/actors"
announcements_iri: "/announcements{/id}"
arguments_iri: "{/root_id}/a{/id}{?destroy}"
arguments_collection_canonical: "{/parent_iri*}/arguments{?filter%5B%5D,page,page_size,type,before}"
arguments_collection_iri: "{/parent_iri*}/arguments{?filter%5B%5D,page,page_size,type,before}"
attachments_collection_canonical: "{/parent_iri*}/attachments{?filter%5B%5D,page,type,before}"
attachments_collection_iri: "{/parent_iri*}/attachments{?filter%5B%5D,page,type,before}"
banners_iri: "{/root_id}/banners{/id}"
banners_collection_canonical: "{/parent_iri*}/banners{?filter%5B%5D,page,page_size,type,before}"
banners_collection_iri: "{/parent_iri*}/banners{?filter%5B%5D,page,page_size,type,before}"
blog_posts_iri: "{/root_id}/posts{/id}{?destroy}"
blog_posts_collection_canonical: "{/parent_iri*}/blog{?filter%5B%5D,page,page_size,type,before}"
blog_posts_collection_iri: "{/parent_iri*}/blog{?filter%5B%5D,page,page_size,type,before}"
comments_iri: "{/root_id}/c{/id}{?destroy,parent_id}"
comments_collection_canonical: "{/parent_iri*}/comments{?filter%5B%5D,page,page_size,type,before}"
comments_collection_iri: "{/parent_iri*}/c{?filter%5B%5D,page,page_size,type,before}"
confirmations_iri: "/users/confirmation"
conversions_iri: "{/parent_iri*}/conversion"
conversions_collection_canonical: "{/parent_iri*}/conversion{?filter%5B%5D,page,page_size,type,before}"
conversions_collection_iri: "{/parent_iri*}/conversion{?filter%5B%5D,page,page_size,type,before}"
con_arguments_iri: "{/root_id}/con{/id}{?destroy}"
con_arguments_collection_canonical: "{/parent_iri*}/con_arguments{?filter%5B%5D,page,page_size,type,before}"
con_arguments_collection_iri: "{/parent_iri*}/cons{?filter%5B%5D,page,page_size,type,before}"
current_actors_iri: "/c_a"
custom_menu_items_iri: "{/parent_iri*}/menus/{menu_type}#custom_{id}"
decisions_iri: "{/parent_iri*}/decision{/id}"
decisions_collection_canonical: "{/parent_iri*}/decision{?page,type,before,state}"
decisions_collection_iri: "{/parent_iri*}/decision{?page,type,before,state}"
delete_iri: "{/parent_iri*}/delete"
direct_messages_iri: "{/parent_iri*}/dm"
direct_messages_collection_canonical: "{/parent_iri*}/dm{?filter%5B%5D,page,page_size,type,before}"
direct_messages_collection_iri: "{/parent_iri*}/dm{?filter%5B%5D,page,page_size,type,before}"
discussions_collection_canonical: "{/parent_iri*}/discussions{?filter%5B%5D,page,page_size,type,before}"
discussions_collection_iri: "{/parent_iri*}/discussions{?filter%5B%5D,page,page_size,type,before}"
documents_iri: "{/name}"
drafts_collection_canonical: "{/parent_iri*}/drafts{?filter%5B%5D,page,page_size,type,before}"
drafts_collection_iri: "{/parent_iri*}/drafts{?filter%5B%5D,page,page_size,type,before}"
edges_iri: "/edges{/id}"
edges_canonical_iri: "/edges{/id}"
edit_iri: "{/parent_iri*}/edit{?form,reset_password_token}"
email_addresses_iri: "{/parent_iri*}/email{/id}"
email_addresses_collection_canonical: "{/parent_iri*}/email_addresses"
email_addresses_collection_iri: "{/parent_iri*}/email_addresses"
export_iri: "{/parent_iri*}/exports"
exports_iri: "{/root_id*}/exports{/id}{?destroy}"
exports_collection_canonical: "{/parent_iri*}/exports{?filter%5B%5D,page,page_size,type,before}"
exports_collection_iri: "{/parent_iri*}/exports{?filter%5B%5D,page,page_size,type,before}"
favorites_iri: "{/root_id}/favorites{/id}"
favorites_collection_canonical: "{/parent_iri*}/favorites{?filter%5B%5D,page,page_size,type,before}"
favorites_collection_iri: "{/parent_iri*}/favorites{?filter%5B%5D,page,page_size,type,before}"
favorites_feed_iri: "/feed"
feeds_iri: "{/parent_iri*}/feed{.format}{?complete}"
follows_iri: "/follows{/id}{?gid,follow_type}"
follows_unsubscribe_iri: "/follows{/id}/unsubscribe"
forums_iri: "{/root_id}{/id}"
forums_collection_canonical: "{/parent_iri*}/forums{?filter%5B%5D,page,page_size,type,before}"
forums_collection_iri: "{/parent_iri*}/forums{?filter%5B%5D,page,page_size,type,before}"
grant_tree_nodes_iri: "/edges{/edge_id}/permissions"
grant_tree_permission_groups_iri: "/edges{/edge_id}/permissions/g{/group_id}"
grant_tree_permissions_iri: "/edges{/edge_id}/permissions/g{/group_id}{/resource_type}"
grants_iri: "{/root_id}/grants{/id}"
grants_collection_canonical: "{/parent_iri*}/grants{?page,type,before,edge_id,group_id}"
grants_collection_iri: "{/parent_iri*}/grants{?page,type,before,edge_id,group_id}"
grant_sets_iri: "/grant_sets{/id}"
grant_sets_collection_iri: "/grant_sets{?page,type,before,edge_id,group_id}"
groups_iri: "{/root_id}/g{/id}"
groups_collection_canonical: "{/parent_iri*}/groups{?filter%5B%5D,page,page_size,type,before}"
groups_collection_iri: "{/parent_iri*}/g{?filter%5B%5D,page,page_size,type,before}"
group_memberships_iri: "{/root_id}/group_memberships{/id}"
group_memberships_collection_canonical: "{/parent_iri*}/group_memberships{?filter%5B%5D,page,page_size,type,before}"
group_memberships_collection_iri: "{/parent_iri*}/group_memberships{?filter%5B%5D,page,page_size,type,before}"
guest_users_iri: "/sessions{/id}"
info_iri: "/i{/id}"
invites_iri: "{/parent_iri*}/invite"
linked_collections_iri: "{/root_id}{/forum}/od{/id}"
linked_collection_members_iri: "{/parent_iri*}{?filter%5B%5D,page,page_size,type,before}"
linked_records_iri: "{/root_id}{/forum_id}/od{/linked_record_id}"
list_items_iri: "/items{/id}"
logs_iri: "{/parent_iri*}/log"
media_objects_iri: "/media_objects{/id}"
media_objects_collection_canonical: "{/parent_iri*}/media_objects{?filter%5B%5D,page,type,before}"
media_objects_collection_iri: "{/parent_iri*}/media_objects{?filter%5B%5D,page,type,before}"
menu_lists_iri: "{/parent_iri*}/menus"
menus_iri: "/menus{/id}"
motions_iri: "{/root_id}/m{/id}{?destroy,start_motion_tour,happening_id}"
motions_collection_canonical: "{/parent_iri*}/motions{?filter%5B%5D,page,page_size,type,before}"
motions_collection_iri: "{/parent_iri*}/m{?filter%5B%5D,page,page_size,type,before}"
move_iri: "{/parent_iri*}/move{?edge_id}"
new_iri: "{/parent_iri*}/new"
notifications_iri: "/n{/id}"
notifications_collection_canonical: "/n{?filter%5B%5D,page,page_size,type,before}"
notifications_collection_iri: "/n{?filter%5B%5D,page,page_size,type,before}"
organizations_finder_iri: "/o/find{?iri}"
page_menu_lists_iri: ""
pages_iri: "{/root_id}"
pages_collection_canonical: "{/parent_iri*}/organizations{?filter%5B%5D,page,page_size,type,before}"
pages_collection_iri: "{/parent_iri*}/o{?filter%5B%5D,page,page_size,type,before}"
passwords_iri: "/users/password"
permitted_actions_iri: "/permitted_actions{/id}{?destroy,start_motion_tour,happening_id}"
permitted_actions_collection_iri: "/permitted_actions{?filter%5B%5D,page,page_size,type,before}"
phases_iri: "/phases{/id}"
places_iri: "/places{/id}"
placements_iri: "/placements{/id}"
placements_collection_canonical: "{/parent_iri*}/placements{?filter%5B%5D,page,page_size,type,before}"
placements_collection_iri: "{/parent_iri*}/placements{?filter%5B%5D,page,page_size,type,before}"
pro_arguments_iri: "{/root_id}/pro{/id}{?destroy}"
pro_arguments_collection_canonical: "{/parent_iri*}/pro_arguments{?filter%5B%5D,page,page_size,type,before}"
pro_arguments_collection_iri: "{/parent_iri*}/pros{?filter%5B%5D,page,page_size,type,before}"
profiles_iri: "/profiles{/id}"
projects_iri: "{/root_id}/p{/id}"
publications_iri: "/publications{/id}"
questions_iri: "{/root_id}/q{/id}{?destroy,happening_id,sort}"
questions_collection_canonical: "{/parent_iri*}/questions{?filter%5B%5D,page,page_size,type,before}"
questions_collection_iri: "{/parent_iri*}/q{?filter%5B%5D,page,page_size,type,before}"
settings_iri: "{/parent_iri*}/settings{?tab}"
shortnames_iri: "/shortnames{/id}"
shortnames_collection_canonical: "{/parent_iri*}/shortnames{?filter%5B%5D,page,page_size,type,before}"
shortnames_collection_iri: "{/parent_iri*}/shortnames{?filter%5B%5D,page,page_size,type,before}"
sources_iri: "{/parent_iri*}/s{/id}"
statistics_iri: "{/parent_iri*}/statistics"
terms_iri: "/terms{?referrer}"
tokens_iri: "/tokens{/secret}"
tokens_collection_iri: "/tokens{/token_type}/g{/group_id}{?page,type,before}"
tokens_bearer_collection_iri: "/tokens/bearer/g{/group_id}{?page,type}"
tokens_email_collection_iri: "/tokens/email/g{/group_id}{?page,type}"
trash_iri: "{/parent_iri*}/trash"
untrash_iri: "{/parent_iri*}/untrash"
users_canonical_iri: "/u{/id}"
users_iri: "{/root}/u{/id}"
vote_iri: "{/parent_iri*}/vote{?for}"
votes_iri: "{/root_id}/votes{/id}"
votes_collection_canonical: "{/parent_iri*}/votes{?filter%5B%5D*,page,type,before,for}"
votes_collection_iri: "{/parent_iri*}/votes{?filter%5B%5D*,page,type,before,for}"
vote_events_iri: "{/parent_iri*}/vote_events{/id}"
vote_events_collection_canonical: "{/parent_iri*}/vote_events{?filter%5B%5D,page,page_size,type,before}"
vote_events_collection_iri: "{/parent_iri*}/vote_events{?filter%5B%5D,page,page_size,type,before}"
vote_matches_iri: "/vote_matches{/id}"
vote_matches_collection_canonical: "{/parent_iri*}/vote_matches{?filter%5B%5D,page,page_size,type,before}"
vote_matches_collection_iri: "{/parent_iri*}/vote_matches{?filter%5B%5D,page,page_size,type,before}"
widgets_iri: "/widgets{/id}"
widgets_collection_canonical: "{/parent_iri*}/widgets{?filter%5B%5D,page,page_size,type,before}"
widgets_collection_iri: "{/parent_iri*}/widgets{?filter%5B%5D,page,page_size,type,before}"
# Argu Service
new_vote: "{/voteable_path*}/votes/new{?confirm,r,vote%5Bfor%5D}"
new_pasword: "/users/password/new"
user_confirmation: "/users/confirmation{?confirmation_token}"
user_confirm: "/users/confirm"
user_registration: "/users"
user_set_password: "/users/password/edit{?reset_password_token}"
user_unlock: "/users/unlock{?unlock_token}"
setup_iri: "/u/setup"
spi_authorize: "/spi/authorize{?resource_type,resource_id,resource_iri,authorize_action}"
spi_oauth_token: "/spi/oauth/token"
spi_email_addresses: "/spi/email_addresses{?email}"
default_vote_event_votes_index: "{/parent_iri*}/vote_events/default"
# Token Service
bearer_token: "/tokens/{access_token}"
verify_token: "/tokens/verify{?jwt}"
# Email Service
email_spi_create: "/email/spi/emails"
email_index: "/email/emails"
