# General IRI's
action_items_iri: "{/parent_iri*}{/id}"
action_lists_iri: "{/parent_iri*}/actions"
activities_iri: "{/root_id}/activities{/id}"
actors_iri: "{/parent_iri*}/actors"
arguments_iri: "{/root_id}/a{/id}{?destroy}"
banners_iri: "{/root_id}/banners{/id}{?destroy}"
banner_dismissals_iri: "{/root_id}/banner_dismissals{/id}{?destroy}"
blog_posts_iri: "{/root_id}/posts{/id}{?destroy}"
budget_shops_iri: "{/root_id}/budgets{/id}{?destroy}"
carts_iri: "{/parent_iri*}/cart{/id}{?destroy}"
cart_details_iri: "{/parent_iri*}/cart_details{?uuid}"
categories_iri: "{/root_id}/categories{/id}{?destroy}"
collection_iri: "{/parent_iri*}/{route_key}{?before%5B%5D*,display,filter%5B%5D*,iri,sort%5B%5D*,page,page_size,title,type}"
comments_iri: "{/root_id}/c{/id}{?destroy,parent_id}"
confirmations_iri: "/u/confirmation{?user%5Bemail%5D,confirmation_token}"
conversions_iri: "{/parent_iri*}/conversion"
con_arguments_iri: "{/root_id}/cons{/id}{?destroy}"
container_nodes_iri: "{/root_id}{/id}{?destroy}"
coupon_batches_iri: "{/root_id}/coupon_batches{/id}{?destroy}"
creative_works_iri: "{/root_id}/creative_works{/id}{?destroy}"
current_actors_iri: "/c_a"
custom_actions_iri: "{/parent_iri*}/custom_actions{/id}{?destroy}"
decisions_iri: "{/parent_iri*}/decisions{/id}{?destroy}"
delete_iri: "{/parent_iri*}/delete"
direct_messages_iri: "{/parent_iri*}/dm"
documents_iri: "{/name}"
edges_iri: "/edges{/id}{?destroy}"
edit_iri: "{/parent_iri*}/edit{?form,reset_password_token}"
email_addresses_iri: "{/parent_iri*}/email_addresses{/id}{?email_address%5Bprimary%5D}"
email_conflicts_iri: "{/parent_iri*}/email_conflict"
export_iri: "{/parent_iri*}/exports"
exports_iri: "{/root_id*}/exports{/id}{?destroy}"
feeds_iri: "{/parent_iri*}/feed{.format}{?complete}"
follows_iri: "{/parent_iri*}/follows{/id}{?follow_type}"
grant_tree_nodes_iri: "/edges{/edge_id}/permissions"
grant_tree_permission_groups_iri: "/edges{/edge_id}/permissions/g{/group_id}"
grant_tree_permissions_iri: "/edges{/edge_id}/permissions/g{/group_id}{/resource_type}"
grants_iri: "{/root_id}/grants{/id}{?destroy}"
grant_sets_iri: "/grant_sets{/id}{?destroy}"
groups_iri: "{/root_id}/g{/id}{?destroy}"
group_memberships_iri: "{/root_id}/group_memberships{/id}{?destroy}"
group_membership_create_iri: "{/root_id}/g{/group_id}/group_memberships{/id}{?destroy}"
guest_users_iri: "/sessions{/id}"
incidents_iri: "{/root_id}/incidents{/id}{?destroy}"
identities_iri: "/identities{/id}"
info_iri: "/i{/id}"
interventions_iri: "{/root_id}/interventies{/id}{?destroy}"
intervention_types_iri: "{/root_id}/interventie_types{/id}{?destroy}"
invites_iri: "{/parent_iri*}/invites"
languages_iri: "/user/language{/language}"
linked_records_iri: "{/root_id}/resource{?iri}"
logs_iri: "{/parent_iri*}/log"
manifests_iri: "{/root_id}/manifest"
measures_iri: "{/root_id}/voorbeelden{/id}{?destroy}"
measure_types_iri: "{/root_id}/measure_types{/id}{?destroy}"
media_objects_iri: "{/root_id}/media_objects{/id}{?destroy}"
menu_lists_iri: "{/parent_iri*}/menus"
menus_iri: "/menus{/id}"
motions_iri: "{/root_id}/m{/id}{?destroy}"
moves_iri: "{/parent_iri*}/move{?move%5Bnew_parent_id%5D}"
new_iri: "{/parent_iri*}/new"
new_container_node_iri: "/container_nodes/new{?before%5B%5D*,display,filter%5B%5D*,iri,sort%5B%5D*,page,page_size,title,type}"
notifications_iri: "/n{/id}{?destroy}"
offers_iri: "{/root_id}/offers{/id}{?destroy}"
ontologies_iri: "{/parent_iri*}/ns/core"
orders_iri: "{/root_id}/orders{/id}{?destroy}"
order_details_iri: "{/root_id}/order_details{/id}{?destroy}"
page_menu_lists_iri: ""
pages_iri: ""
passwords_iri: "/u/password"
permitted_actions_iri: "/permitted_actions{/id}{?destroy}"
phases_iri: "/phases{/id}{?destroy}"
places_iri: "/places{/id}{?destroy}"
placements_iri: "/placements{/id}{?destroy}"
policy_agreements_iri: "/policy_agreements"
pro_arguments_iri: "{/root_id}/pros{/id}{?destroy}"
profiles_iri: "/profiles{/id}"
projects_iri: "{/root_id}/projects{/id}{?destroy}"
publications_iri: "/publications{/id}"
questions_iri: "{/root_id}/q{/id}{?destroy,sort}"
settings_iri: "{/parent_iri*}/settings{?tab}"
shortnames_iri: "/shortnames{/id}{?destroy}"
sources_iri: "{/parent_iri*}/s{/id}{?destroy}"
statistics_iri: "{/parent_iri*}/statistics"
submission_iri: "{/parent_iri*}/submission{?submission%5Bstatus%5D}"
submissions_iri: "{/parent_iri*}/submissions{/id}{?destroy,submission%5Bstatus%5D}"
submissions_collection_canonical: "{/parent_iri*}/submissions{?before%5B%5D*,display,filter%5B%5D*,iri,sort%5B%5D*,page,page_size,title,type}"
surveys_iri: "{/root_id}/surveys{/id}{?destroy}"
terms_iri: "{/root_id}/terms{/id}{?destroy}"
risks_iri: "{/root_id}/gevaren{/id}{?destroy}"
scenarios_iri: "{/root_id}/scenarios{/id}{?destroy}"
setups_iri: "/user/setup"
topics_iri: "{/root_id}/t{/id}{?destroy}"
trash_iri: "{/parent_iri*}/trash"
untrash_iri: "{/parent_iri*}/untrash"
users_iri: "{/root_id}/u{/id}{?destroy}"
vocabularies_iri: "{/root_id}/vocab{/id}{?destroy,sort}"
vote_iri: "{/parent_iri*}/vote{?for}"
votes_iri: "{/root_id}/votes{/id}{?destroy}"
vote_events_iri: "{/parent_iri*}/vote_events{/id}{?destroy}"
widgets_iri: "/widgets{/id}{?destroy}"
# Argu Service
new_vote: "{/voteable_path*}/votes/new{?confirm,redirect_url,vote%5Bfor%5D}"
new_pasword: "/u/password/new"
user_confirmation: "/u/confirmation{?confirmation_token}"
user_connect: "/u{/id}/connect{?token}"
user_registration: "/u/registration"
user_set_password: "/u/password/edit{?reset_password_token}"
user_sign_in: "/u/session/new{?redirect_url}"
user_unlock: "/u/unlock{?unlock_token}"
search_results_iri: "{/parent_iri*}/search{?match,q,filter%5B%5D*,iri,sort%5B%5D*,page,page_size}"
setup_iri: "/user/setup"
spi_authorize: "/spi/authorize{?resource_type,resource_id,resource_iri,authorize_action}"
spi_find_tenant: "/_public/spi/find_tenant{?iri}"
spi_email_addresses: "/spi/email_addresses{?email}"
default_vote_event_votes_index: "{/parent_iri*}/vote_events/default"
oauth_token: "/oauth/token"
# Token Service
tokens_collection_iri: "/tokens/g{/group_id}{/token_type}{?before%5B%5D*,display,page,type}"
verify_token: "{/root_id}/tokens/verify{?jwt}"
# Email Service
email_spi_create: "/email/spi/emails"
email_index: "/email/emails"
