# General IRI's
activities_iri: "/activities{/id}"
actions_iri: "{/parent_iri*}{#type}"
action_lists_iri: "{/parent_iri*}/actions"
announcements_iri: "/announcements{/id}"
arguments_iri: "/a{/id}"
arguments_collection_canonical: "{/parent_iri*}/arguments{?filter%5Boption%5D,page,type,before}"
arguments_collection_iri: "{/parent_iri*}/a{?filter%5Boption%5D,page,type,before}"
banners_iri: "/banners{/id}"
blog_posts_collection_canonical: "{/parent_iri*}/posts{?page,type,before}"
blog_posts_collection_iri: "{/parent_iri*}/posts{?page,type,before}"
blog_posts_iri: "/posts{/id}"
comments_iri: "/c{/id}"
comments_collection_canonical: "{/parent_iri*}/comments{?page,type,before}"
comments_collection_iri: "{/parent_iri*}/c{?page,type,before}"
current_actors_iri: "/c_a"
custom_menu_items_iri: "{/parent_iri*}/menus/{menu_type}#custom_{id}"
decisions_iri: "{/parent_iri*}/decision{/id}"
decisions_collection_canonical: "{/parent_iri*}/decisions{?page,type,before}"
decisions_collection_iri: "{/parent_iri*}/decisions{?page,type,before}"
discussions_collection_canonical: "{/parent_iri*}/discussions{?page,type,before}"
discussions_collection_iri: "{/parent_iri*}/discussions{?page,type,before}"
edges_iri: "/edges{/id}"
email_addresses_iri: "{/parent_iri}/email{/id}"
favorites_iri: "/favorites{/id}"
favorites_feed_iri: "/feed"
feed_iri: "{/parent_iri*}/feed"
follows_iri: "/follows{/id}"
follows_unsubscribe_iri: "/follows{/id}/unsubscribe"
forums_iri: "{/shortname}"
forums_collection_canonical: "{/parent_iri*}/forums{?page,type,before}"
forums_collection_iri: "{/parent_iri*}/forums{?page,type,before}"
grant_tree_nodes_iri: "/edges{/edge_id}/permissions"
grant_tree_permission_groups_iri: "/edges{/edge_id}/permissions/g{/group_id}"
grant_tree_permissions_iri: "/edges{/edge_id}/permissions/g{/group_id}{/resource_type}"
grants_iri: "/grants{/id}"
groups_iri: "/g{/id}"
group_memberships_iri: "/group_memberships{/id}"
guest_users_iri: "/sessions{/id}"
info_iri: "/i{/id}"
linked_collections_iri: "{/organization}{/forum}/od{/id}"
linked_records_iri: "{/organization}{/forum}/od{/linked_record_id}"
list_items_iri: "/items{/id}"
logs_iri: "/log{/edge_id}"
media_objects_iri: "/media_objects{/id}"
media_objects_collection_canonical: "{/parent_iri*}/media_objects{?filter%5Bused_as%5D,page,type,before}"
media_objects_collection_iri: "{/parent_iri*}/media_objects{?filter%5Bused_as%5D,page,type,before}"
menu_lists_iri: "{/parent_iri*}/menus"
menus_iri: "/menus{/id}"
motions_iri: "/m{/id}"
motions_collection_canonical: "{/parent_iri*}/motions{?page,type,before}"
motions_collection_iri: "{/parent_iri*}/m{?page,type,before}"
notifications_iri: "/n{/id}"
notifications_collection_canonical: "/n{?page,type,before}"
notifications_collection_iri: "/n{?page,type,before}"
organizations_finder_iri: "/o/find{?iri}"
page_menu_lists_iri: ""
pages_iri: "/o{/shortname}"
pages_collection_canonical: "/organizations{?page,type,before}"
pages_collection_iri: "/o{?page,type,before}"
phases_iri: "/phases{/id}"
projects_iri: "/p{/id}"
publications_iri: "/publications{/id}"
questions_iri: "/q{/id}"
questions_collection_canonical: "{/parent_iri*}/questions{?page,type,before}"
questions_collection_iri: "{/parent_iri*}/q{?page,type,before}"
shortnames_iri: "/shortames{/id}"
sources_iri: "{/parent_iri*}/s{/id}"
statistics_iri: "{/parent_iri*}/statistics"
tokens_iri: "/tokens{/secret}"
tokens_bearer_collection_iri: "/bearer/g{/group_id}{?page,type}"
tokens_email_collection_iri: "/email/g{/group_id}{?page,type}"
users_canonical_iri: "/u{/id}"
users_iri: "/u{/shortname}"
vote_iri: "{/parent_iri*}/vote"
votes_iri: "/v{/id}"
votes_collection_canonical: "{/parent_iri*}/votes{?filter%5Boption%5D,page,type,before}"
votes_collection_iri: "{/parent_iri*}/v{?filter%5Boption%5D,page,type,before}"
vote_events_iri: "{/parent_iri*}/vote_events{/id}"
vote_events_collection_canonical: "{/parent_iri*}/vote_events{?page,type,before}"
vote_events_collection_iri: "{/parent_iri*}/vote_events{?page,type,before}"
vote_matches_iri: "/vote_matches{/id}"
vote_matches_collection_canonical: "{/parent_iri*}/vote_matches{?page,type,before}"
vote_matches_collection_iri: "{/parent_iri*}/vote_matches{?page,type,before}"
widgets_iri: "/widgets{/id}"
# Argu Service
new_vote: "{/voteable_path*}/votes/new{?confirm,r,vote%5Bfor%5D}"
user_confirmation: "/users/confirmation{?confirmation_token}"
user_confirm: "/users/confirm"
user_registration: "/users"
user_set_password: "/users/password/edit{?reset_password_token}"
user_unlock: "/users/unlock{?unlock_token}"
spi_authorize: "/spi/authorize{?resource_type,resource_id,resource_iri,authorize_action}"
default_vote_event_votes_index: "{/parent_iri*}/vote_events/default"
# Token Service
bearer_token: "/tokens/{access_token}"
verify_token: "/tokens/verify{?jwt}"
# Email Service
email_spi_create: "/email/spi/emails"
email_index: "/email/emails"
