# General IRI's
activities_iri: "/activities{/id}"
actions_iri: "{+parent_iri}{#type}"
action_lists_iri: "{+parent_iri}/actions"
announcements_iri: "/announcements{/id}"
arguments_iri: "/a{/id}"
banners_iri: "/banners{/id}"
blog_posts_iri: "/posts{/id}"
comments_iri: "/comments{/id}"
current_actors_iri: "/c_a"
decisions_iri: "{+parent_iri}/decision{/id}"
email_addresses_iri: "{/parent_iri}/email{/id}"
favorites_iri: "/favorites{/id}"
favorites_feed_iri: "/feed"
feed_iri: "{+parent_iri}/feed"
follows_iri: "/follows{/id}"
follows_unsubscribe_iri: "/follows{/id}/unsubscribe"
forums_iri: "/f{/id}"
grants_iri: "/grants{/id}"
groups_iri: "/g{/id}"
group_memberships_iri: "/group_memberships{/id}"
info_iri: "/i{/id}"
linked_records_iri: "/lr{/id}"
list_items_iri: "/items{/id}"
logs_iri: "/log{/edge_id}"
media_objects_iri: "/media_objects{/id}"
menu_lists_iri: "{+parent_iri}/menus"
menus_iri: "/menus{/id}"
submenus_iri: "{+parent_iri}/menus{/id}"
motions_iri: "/m{/id}"
notifications_iri: "/n{/id}"
organizations_finder_iri: "/o/find{?iri}"
page_menu_lists_iri: ""
pages_iri: "/o{/id}"
phases_iri: "/phases{/id}"
projects_iri: "/p{/id}"
questions_iri: "/q{/id}"
sources_iri: "{+parent_iri}/s{/id}"
statistics_iri: "{+parent_iri}/statistics"
users_iri: "/u{/id}"
vote_iri: "{+parent_iri}/vote"
votes_iri: "/v{/id}"
vote_events_iri: "/vote_events{/id}"
vote_matches_iri: "/vote_matches{/id}"
# Argu Service
new_vote: "{/voteable_path*}/votes/new{?confirm,r,vote%5Bfor%5D}"
user_confirmation: "/users/confirmation{?confirmation_token}"
user_confirm: "/users/confirm"
user_registration: "/users"
user_set_password: "/users/password/edit{?reset_password_token}"
user_unlock: "/users/unlock{?unlock_token}"
spi_authorize: "/spi/authorize{?resource_type,resource_id,resource_iri,authorize_action}"
# Token Service
bearer_token: "/tokens/{access_token}"
verify_token: "/tokens/verify{?jwt}"
# Email Service
email_spi_create: "/email/spi/emails"
email_index: "/email/emails"
