# Argu Service
new_vote: "{/voteable_path*}/votes/new{?confirm,r,vote%5Bfor%5D}"
user_confirmation: "/users/confirmation{?confirmation_token}"
user_confirm: "/users/confirm"
user_registration: "/users"
spi_authorize: "/spi/authorize{?resource_type,resource_id,resource_iri,authorize_action}"
# Token Service
bearer_token: "/tokens/{access_token}"
verify_token: "/tokens/verify{?jwt}"
